export enum Genre {
  SCIENCE_FICTION = 'SCIENCE_FICTION',
  THRILLER = 'THRILLER',
  COMEDY = 'COMEDY',
  MYSTERY = 'MYSTERY',
  CRIME = 'CRIME',
  ROMANCE = 'ROMANCE',
  BIOGRAPHY = 'BIOGRAPHY',
  ADVENTURE = 'ADVENTURE',
  CHILDREN_LITERATURE = 'CHILDREN_LITERATURE'
}
